### ISSUE TITLE
Would this help me achieve VSCode Intellisense for my JSDoc-annotated angular1 project?

### ISSUE THREAD

**Issue by replete** [jumpinjackie/jsdoc-typescript-plugin#80]
I have an AngularJS (1.x) project.
Angular typings enable Intellisense in VSCode.
VSCode automatically uses intellisense from JSDoc annnotations.

I would like to find a way to let VSCode know where all the files containing JSDoc annotations are, so I can have Intellisense in my project.

Here's an example of where it doesn't work:

```js:
// file: /some/dir/myHelper.js
'use strict';

angular.module('myApp').factory('myHelper', [ 'thing', 'thing2', myHelper]);

function myHelper(thing1, thing2) {
  
  /**
   * @param  {number} a - factor 1
   * @param  {number} b - factor 2
   * @returns {number}
   */
  function getThing(a, b) {
    return a * b;
  }

  var x = getThing(100, 200); // VSCode intellisense works here

  return {
    getThing: getThing
  };
}
```

```js
// file: /some/other/dir/otherModule.js
'use strict';
angular.module('myApp.otherThing')
.factory('otherThingInterceptor', ['$q', 'thing1', 'thing2', 'myHelper',
    function($q, thing1, thing2, myHelper) {

    myHelper.getThing(100, 200); // No intellisense

    }
]);
```

Will this tool help with this objective? 

Does anyone have experience with this?

**Comment by jumpinjackie** [comment]
The short answer is: Probably not

If you run JSDoc against that source right now, I'm pretty sure it will pick up and generate API documentation for `getThing`. What it probably won't do, and is probably the deal-breaker in this situation is figure out what the "shape" of the module that has this function called `getThing`. It will know that there's a function called `getThing`, but not know about the `myHelper` module that contains it.

This plugin merely piggybacks off of the comment/documentation processing work that JSDoc does so I'm probably thinking this will find a documented function named `getThing` in your source but because neither JSDoc or this plugin have any idea what the actual module shape is, it will just chuck this declaration into the global namespace when emitting out the d.ts file.

**Comment by replete** [comment]
It seems I need something to generate typings for angular project, which of course, understands angular.
 
VSCode might pickup the JSDoc annotations, seems to be automatic.

I will continue my search. Thanks for your help.
